### ISSUE TITLE
android device version 

### ISSUE THREAD

**Issue by AtlasMaxima-zz** [douglasjunior/react-native-easybluetooth-classic#13]
Does this package only works for Android 4.1 (API 16) ? 
 
i.e. it won't work for Android 6 Marshmallow ?

**Comment by douglasjunior** [comment]
Works on Android API 16 or greather.

Note that in Android API 23 or greather you need make sure that location is enabled: 

https://github.com/douglasjunior/react-native-easybluetooth-classic#known-issues

**Comment by AtlasMaxima-zz** [comment]
The location only needs to be enabled for BLE devices or also classic Bluetooth devices?  - which I am attempting to use this package for.

**Comment by douglasjunior** [comment]
You can test, but I believe it is both.

**Comment by aidooyaw1992** [comment]
Please I'm able to scan for devices, I'm able to find devices but cannot connect, I always get EUNSPECIFIED

**Comment by stephane-r** [comment]
Same issue, anyone have other result ?

**Comment by douglasjunior** [comment]
I will close this issue because he original question is:

> Does this package only works for Android 4.1 (API 16) ?

So, please, open a new issue for a new question.
