### ISSUE TITLE
Connecting to other devices.

### ISSUE THREAD

**Issue by buzzer-re** [douglasjunior/react-native-easybluetooth-classic#15]
Can i scan devices without init the config ? i'm using more than just one HC-05 with differents names.

Getting that when i try to scan:
```Error: BluetoothService has not been configured. Call ReactNativeEasyBluetooth.init(config).```

**Comment by douglasjunior** [comment]
Different names are not a problem.

The `name` that you need to configure is the name of your App, and not the name of the remotes devices.

**Comment by AandersonL** [comment]
Sunddely this error stoped, and now is working. i will close this issue.
thx
