### ISSUE TITLE
[ Question ] What is state of this project?

### ISSUE THREAD

**Issue by esutton** [douglasjunior/react-native-easybluetooth-classic#2]
I could not find any Apple APIs or Android APIs needed to supporting Bluetooth Classic on iOS and Android.

I assume this project is under development?

Thanks for sharing your work.

**Comment by douglasjunior** [comment]
Both [Classic](https://github.com/douglasjunior/react-native-easybluetooth-classic) and [BLE](https://github.com/douglasjunior/react-native-easybluetooth-le) are in production in some projects, but only for Android for now. This library is a wrap of the [AndroidBluetoothLibrary](https://github.com/douglasjunior/AndroidBluetoothLibrary).

I have plans to implement BLE for iOS, but I have no iOS device in the moment. Maybe in the next few months.

Collaborations are welcome!
