### ISSUE TITLE
[Question] Is possible to disconnect?

### ISSUE THREAD

**Issue by renanborgez** [douglasjunior/react-native-easybluetooth-classic#22]
## Question

Hello,
I started to use your plugin and everything is going very well until now. i just want to wonder if is possible to `disconnect` from a device? I know there is no documentation for it, but i just want to know if it is possible

i'm trying to call: 
```
EasyBluetooth.disconnect(device)
```

But i'm receiving the following error
```
EasyBluetoothClassic.disconnect got 3 arguments, expected 2
```

**Comment by douglasjunior** [comment]
Hi, thanks for reporting.

I'll take a look soon.

**Comment by renanborgez** [comment]
I know that there is no documentation for `disconnect` inside your README file
But i'm wondering because it could be very useful :)

**Comment by douglasjunior** [comment]
Sorry, now I got the problem.

You can't pass arguments to the function `disconnect`.

https://github.com/douglasjunior/react-native-easybluetooth-classic/blob/8971d151920f4f4749863f271c957ca35c26d40d/android/src/main/java/io/github/douglasjunior/ReactNativeEasyBluetooth/classic/ClassicModule.java#L55-L59

**Comment by renanborgez** [comment]
May i open a pull request to put it on your documentation?

**Comment by douglasjunior** [comment]
Sure, thanks!

**Comment by renanborgez** [comment]
:)
