### ISSUE TITLE
Issue running ./gradlew assembleRelease

### ISSUE THREAD

**Issue by molimat** [douglasjunior/react-native-easybluetooth-classic#26]
Hey Douglas,
I'm using this library, which is perfect for what i've been doing, but when i'm assemblying within an apk, I get some issue related to appcombat. I've tried everything I found on internet (Changing and downloading sdk versions and so on), is that a library issue related to outdate of the version?

> C:\Users\mathe\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\d54b9b7a5c80bd4b98d989f9ae5b97e0\res\values-v26\values-v26.xml:9:5-12:13: AAPT: resource android:attr/colorError not found.
C:\Users\mathe\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\d54b9b7a5c80bd4b98d989f9ae5b97e0\res\values-v26\values-v26.xml:13:5-16:13: AAPT: resource android:attr/colorError not found.
C:\Users\mathe\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\d54b9b7a5c80bd4b98d989f9ae5b97e0\res\values-v26\values-v26.xml:17:5-93: AAPT: style attribute 'android:attr/keyboardNavigationCluster' not found.
C:\Users\mathe\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\d54b9b7a5c80bd4b98d989f9ae5b97e0\res\values\values.xml:251:5-69: AAPT: resource android:attr/fontStyle not found.
C:\Users\mathe\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\d54b9b7a5c80bd4b98d989f9ae5b97e0\res\values\values.xml:251:5-69: AAPT: resource android:attr/font not found.
C:\Users\mathe\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\d54b9b7a5c80bd4b98d989f9ae5b97e0\res\values\values.xml:251:5-69: AAPT: resource android:attr/fontWeight not found.
error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
C:\Users\mathe\Desktop\ESTUDOS\Udemy\React-Native\SmartTags\node_modules\easy-bluetooth-classic\android\build\intermediates\res\merged\release\values-v26\values-v26.xml:7: error: resource android:attr/colorError not found.
C:\Users\mathe\Desktop\ESTUDOS\Udemy\React-Native\SmartTags\node_modules\easy-bluetooth-classic\android\build\intermediates\res\merged\release\values-v26\values-v26.xml:11: error: resource android:attr/colorError not found.
C:\Users\mathe\Desktop\ESTUDOS\Udemy\React-Native\SmartTags\node_modules\easy-bluetooth-classic\android\build\intermediates\res\merged\release\values-v26\values-v26.xml:15: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
C:\Users\mathe\Desktop\ESTUDOS\Udemy\React-Native\SmartTags\node_modules\easy-bluetooth-classic\android\build\intermediates\res\merged\release\values\values.xml:226: error: resource android:attr/fontStyle not found.
C:\Users\mathe\Desktop\ESTUDOS\Udemy\React-Native\SmartTags\node_modules\easy-bluetooth-classic\android\build\intermediates\res\merged\release\values\values.xml:226: error: resource android:attr/font not found.
C:\Users\mathe\Desktop\ESTUDOS\Udemy\React-Native\SmartTags\node_modules\easy-bluetooth-classic\android\build\intermediates\res\merged\release\values\values.xml:226: error: resource android:attr/fontWeight not found.

**Comment by molimat** [comment]
Just solved that issue.
If someone else is facing the same situation, you have to add this code on you /android/build.gradle, right below "allprojects" brackets:

```
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 27
                buildToolsVersion "27.0.2"
            }
        }
    }
}
```

**Comment by douglasjunior** [comment]
Thanks @molimat , sorry for delay.

I need to update the Sdk version in this library.
