### ISSUE TITLE
The development server returned response error code: 500

### ISSUE THREAD

**Issue by zhanyulong** [douglasjunior/react-native-easybluetooth-classic#5]
![screenshot_1503898288](https://user-images.githubusercontent.com/6070885/29760341-365e8ae4-8bf5-11e7-80f9-599ac1cfe42d.png)

**Comment by douglasjunior** [comment]
I still do not know why, but in the newer versions of React Native its starting with `babel-preset-react-native`  version `3.0.0` or `2.0.1`.

These versions do not support some of the features we're used. To solve, just update to version `2.1.0`.

```bash
yarn add babel-preset-react-native@2.1.0
```
Or
```bash
npm install --save babel-preset-react-native@2.1.0
```

**Comment by zhanyulong** [comment]
fixed my issue! Thx @douglasjunior !

**Comment by mehtapcelik284** [comment]
My app's problem was solved too.
Thanks a lot @douglasjunior !

**Comment by psobhanlo** [comment]
Thanks a lot @douglasjunior ! solved
`npm install --save babel-preset-react-native@2.1.0`

**Comment by maniyarpayal** [comment]
@psobhanlo  million Thanks! This solves my issue.

**Comment by komalsakhiya** [comment]
this not solves mt issue
