### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by Yhozen** [douglasjunior/react-native-easybluetooth-classic#7]
I don't know if I'm doing something wrong but after the installation process I get this error

> /home/garox/Documents/def/android/app/src/main/java/com/def/MainApplication.java:6: error: cannot find symbol
import com.facebook.react.ReactApplication;
                         ^
  symbol:   class ReactApplication
  location: package com.facebook.react
/home/garox/Documents/def/android/app/src/main/java/com/def/MainApplication.java:9: error: cannot find symbol
import com.facebook.react.ReactNativeHost;
                         ^
  symbol:   class ReactNativeHost
  location: package com.facebook.react
/home/garox/Documents/def/android/app/src/main/java/com/def/MainApplication.java:17: error: cannot find symbol
public class MainApplication extends Application implements ReactApplication {
                                                            ^
  symbol: class ReactApplication
/home/garox/Documents/def/android/app/src/main/java/com/def/MainApplication.java:19: error: cannot find symbol
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
                ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/home/garox/Documents/def/android/app/src/main/java/com/def/MainApplication.java:35: error: cannot find symbol
  public ReactNativeHost getReactNativeHost() {
         ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/home/garox/Documents/def/android/app/src/main/java/com/def/MainActivity.java:5: error: MainActivity is not abstract and does not override abstract method getPackages() in ReactActivity
public class MainActivity extends ReactActivity {
       ^
/home/garox/Documents/def/android/app/src/main/java/com/def/MainApplication.java:19: error: cannot find symbol
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
                                                       ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/home/garox/Documents/def/android/app/src/main/java/com/def/MainApplication.java:34: error: method does not override or implement a method from a supertype
  @Override
  ^
8 errors
:app:compileDebugJavaWithJavac FAILED

I believe it's related to jitpack

**Comment by douglasjunior** [comment]
Sorry for delay. I think you've already solved the problem, if not, please let me know.
